name: Trigger auto deployment for madi-consultancy

on:
  push:
    branches: 
      [ main ]
    paths:
    - 'microservices/**'
    - '.github/workflows/madi-consultancy-AutoDeployTrigger-92f182c3-8df2-436a-815a-a8988115db83.yml'

  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MADICONSULTANCY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MADICONSULTANCY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MADICONSULTANCY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          # This line tells Azure to look inside your new folder
          appSourcePath: ${{ github.workspace }}/microservices
          containerAppName: madi-consultancy
          resourceGroup: DefaultResourceGroup-CHN
          imageToBuild: madi-consultancy:${{ github.sha }}
          registryUrl: # Ensure your registry URL is here if required by your setup
          registryUsername: ${{ secrets.MADICONSULTANCY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MADICONSULTANCY_REGISTRY_PASSWORD }}
